# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans
  title: 叶凡的学术主页
  params:
    description: 叶凡的个人学术网站

# English version (optional)
en:
  languageCode: en-us
  title: Ye Fan's Academic Homepage
  params:
    description: Ye Fan's Personal Academic Website
